### ISSUE TITLE
Request pretrained models

### ISSUE THREAD

**Issue by zcode86** [toandaominh1997/EfficientDet.Pytorch#122]
I can not download the D0-D7 pth pretrained models because of the connection, who can provide them to me? Thanks .
2071413919@qq.com   /
midgpower@gmail.com

**Comment by yanghoJI** [comment]
@iamastar88 
check [here](https://www.kaggle.com/raghaw/efficientnet-pytorch-b0-b7/version/1#efficientnet-b0-355c32eb.pth)

**Comment by KelvinHuang666** [comment]
python train.py --dataset VOC --dataset_root data/VOCdevkit/ --network efficientdet-d4 --batch_size
12 --gpu 7
train.py:304: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
train.py:311: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Use GPU: 7 for training
Downloading: "http://storage.googleapis.com/public-models/efficientnet/efficientnet-b4-6ed6700e.pth" to /root/.cache/torch/checkpoints/efficientnet-b4-6ed6700e.pth
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    main()
  File "train.py", line 331, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 234, in main_worker
    D_class=EFFICIENTDET[args.network]['D_class']
  File "/asff/EfficientDet.Pytorch-master/models/efficientdet.py", line 33, in __init__
    self.backbone = EfficientNet.from_pretrained(MODEL_MAP[network])
  File "/asff/EfficientDet.Pytorch-master/models/efficientnet.py", line 243, in from_pretrained
    model, model_name, load_fc=(num_classes == 1000))
  File "/asff/EfficientDet.Pytorch-master/models/utils.py", line 319, in load_pretrained_weights
    state_dict = model_zoo.load_url(url_map[model_name])
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 462, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 372, in _download_url_to_file
    u = urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
U can download with 迅雷。+ http://storage.googleapis.com/public-models/efficientnet/efficientnet-b4-6ed6700e.pth
But I try val mAP=0 ，except D0 and D1。
good luck。

**Comment by lvpinrui** [comment]
> python train.py --dataset VOC --dataset_root data/VOCdevkit/ --network efficientdet-d4 --batch_size
> 12 --gpu 7
> train.py:304: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
> warnings.warn('You have chosen to seed training. '
> train.py:311: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
> warnings.warn('You have chosen a specific GPU. This will completely '
> Use GPU: 7 for training
> Downloading: "http://storage.googleapis.com/public-models/efficientnet/efficientnet-b4-6ed6700e.pth" to /root/.cache/torch/checkpoints/efficientnet-b4-6ed6700e.pth
> Traceback (most recent call last):
> File "train.py", line 335, in
> main()
> File "train.py", line 331, in main
> main_worker(args.gpu, ngpus_per_node, args)
> File "train.py", line 234, in main_worker
> D_class=EFFICIENTDET[args.network]['D_class']
> File "/asff/EfficientDet.Pytorch-master/models/efficientdet.py", line 33, in **init**
> self.backbone = EfficientNet.from_pretrained(MODEL_MAP[network])
> File "/asff/EfficientDet.Pytorch-master/models/efficientnet.py", line 243, in from_pretrained
> model, model_name, load_fc=(num_classes == 1000))
> File "/asff/EfficientDet.Pytorch-master/models/utils.py", line 319, in load_pretrained_weights
> state_dict = model_zoo.load_url(url_map[model_name])
> File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 462, in load_state_dict_from_url
> _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
> File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 372, in _download_url_to_file
> u = urlopen(url)
> File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
> return opener.open(url, data, timeout)
> File "/usr/lib/python3.6/urllib/request.py", line 532, in open
> response = meth(req, response)
> File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
> 'http', request, response, code, msg, hdrs)
> File "/usr/lib/python3.6/urllib/request.py", line 570, in error
> return self._call_chain(*args)
> File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
> result = func(*args)
> File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
> raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden
> U can download with 迅雷。+ http://storage.googleapis.com/public-models/efficientnet/efficientnet-b4-6ed6700e.pth
> But I try val mAP=0 ，except D0 and D1。
> good luck。

can you give me D0-D7 pth pretrained models ?please,thank you very much?

**Comment by lvpinrui** [comment]
> I can not download the D0-D7 pth pretrained models because of the connection, who can provide them to me? Thanks .
> [2071413919@qq.com](mailto:2071413919@qq.com) /
> [midgpower@gmail.com](mailto:midgpower@gmail.com)

Do you get those Pth? if yes,Please send me a copy?  
wait for your reply,thanks!

**Comment by zylo117** [comment]
> > I can not download the D0-D7 pth pretrained models because of the connection, who can provide them to me? Thanks .
> > [2071413919@qq.com](mailto:2071413919@qq.com) /
> > [midgpower@gmail.com](mailto:midgpower@gmail.com)
> 
> Do you get those Pth? if yes,Please send me a copy?
> wait for your reply,thanks!

checkout my repo, 
The pytorch re-implement of the official efficientdet with SOTA performance in real time and pretrained weights.

there are D0-D7 weights

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch

**Comment by lvpinrui** [comment]
thank  you very  much！ 1358420042 邮箱1358420042@qq.com 签名由 网易邮箱大师 定制 On 04/11/2020 13:13, zylo117 wrote: I can not download the D0-D7 pth pretrained models because of the connection, who can provide them to me? Thanks . 2071413919@qq.com / midgpower@gmail.com Do you get those Pth? if yes,Please send me a copy? wait for your reply,thanks! checkout my repo, The pytorch re-implement of the official efficientdet with SOTA performance in real time and pretrained weights. there are D0-D7 weights https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
