### ISSUE TITLE
When i load pretrained weights to run demo.py，something went wrong.

### ISSUE THREAD

**Issue by frederichen01** [toandaominh1997/EfficientDet.Pytorch#127]
I load the efficientnet-b0-355c32eb.pth or efficientnet-b7-dcc49843.pth, the command line print KeyError: 'parser'.More details as fellow, could you help me?
Load pretrained Model
Traceback (most recent call last):
  File "demo.py", line 174, in <module>
    detect = Detect(weights=args.weight)
  File "demo.py", line 52, in __init__
    params = checkpoint['parser']
KeyError: 'parser'

**Comment by m-petuhov** [comment]
It work for me: just change this lines
```python
params = checkpoint['parser'] 
num_class = params.num_class
network = params.network
```
to
```python
num_class = checkpoint['num_class']
network = checkpoint['network']
```
But you can't run `efficientnet-b7` with `checkpoint_VOC_efficientdet-d1_97.pth`, maybe you have checkpoints for `efficientdet-d7`? If yes, can you share them here?

**Comment by R4ZZ3** [comment]
@m-petuhov  Can you give example.
If I want to run efficientdet-d6 what arguments should I use.
I made the replacements you mentioned but still get error: 

Traceback (most recent call last):
  File "demo.py", line 180, in <module>
    detect = Detect(weights=args.weight)
  File "demo.py", line 52, in __init__
    num_class = checkpoint['num_class']
KeyError: 'num_class'

I tried this:
python demo.py --network efficientdet-d6 --weight ./efficientnet-b0-355c32eb.pth --iou_threshold 0.5 --threshold 0.5 --cam ./test_racing.mp4
