### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by SlowMonk** [toandaominh1997/EfficientDet.Pytorch#155]
```
(venv) jake@jake-ubuntu:~/Gits/EfficientDet.Pytorch$ python train.py --network efficientdet-d0  # Example
train.py:302: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
Downloading: "http://storage.googleapis.com/public-models/efficientnet/efficientnet-b0-355c32eb.pth" to /home/jake/.cache/torch/hub/checkpoints/efficientnet-b0-355c32eb.pth
Traceback (most recent call last):
  File "train.py", line 333, in <module>
    main()
  File "train.py", line 329, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 232, in main_worker
    D_class=EFFICIENTDET[args.network]['D_class']
  File "/home/jake/Gits/EfficientDet.Pytorch/models/efficientdet.py", line 33, in __init__
    self.backbone = EfficientNet.from_pretrained(MODEL_MAP[network])
  File "/home/jake/Gits/EfficientDet.Pytorch/models/efficientnet.py", line 243, in from_pretrained
    model, model_name, load_fc=(num_classes == 1000))
  File "/home/jake/Gits/EfficientDet.Pytorch/models/utils.py", line 319, in load_pretrained_weights
    state_dict = model_zoo.load_url(url_map[model_name])
  File "/home/jake/venv/lib/python3.6/site-packages/torch/hub.py", line 483, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/jake/venv/lib/python3.6/site-packages/torch/hub.py", line 381, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by failable** [comment]
Same issue...

**Comment by nenoNaninu** [comment]
See this issue. https://github.com/toandaominh1997/EfficientDet.Pytorch/issues/148#issuecomment-653854405
