### ISSUE TITLE
what the ***k!

### ISSUE THREAD

**Issue by huangweiji2019** [toandaominh1997/EfficientDet.Pytorch#57]
my number_class is 3(1bg+2classes)。eval is error and demo.py not work!  which para error?

Loading checkpoint: ./weights/Final_efficientdet-d4.pth ...
Loaded pretrained weights for efficientnet-b4
Traceback (most recent call last):
  File "eval.py", line 72, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDet:
	Unexpected key(s) in state_dict: "neck.stack_bifpn_convs.3.w1", "neck.stack_bifpn_convs.3.w2", "neck.stack_bifpn_convs.3.bifpn_convs.0.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.0.0.conv.bias", "neck.stack_bifpn_convs.3.bifpn_convs.1.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.1.0.conv.bias", "neck.stack_bifpn_convs.3.bifpn_convs.2.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.2.0.conv.bias", "neck.stack_bifpn_convs.3.bifpn_convs.3.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.3.0.conv.bias", "neck.stack_bifpn_convs.3.bifpn_convs.4.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.4.0.conv.bias", "neck.stack_bifpn_convs.3.bifpn_convs.5.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.5.0.conv.bias", "neck.stack_bifpn_convs.3.bifpn_convs.6.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.6.0.conv.bias", "neck.stack_bifpn_convs.3.bifpn_convs.7.0.conv.weight", "neck.stack_bifpn_convs.3.bifpn_convs.7.0.conv.bias", "neck.stack_bifpn_convs.4.w1", "neck.stack_bifpn_convs.4.w2", "neck.stack_bifpn_convs.4.bifpn_convs.0.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.0.0.conv.bias", "neck.stack_bifpn_convs.4.bifpn_convs.1.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.1.0.conv.bias", "neck.stack_bifpn_convs.4.bifpn_convs.2.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.2.0.conv.bias", "neck.stack_bifpn_convs.4.bifpn_convs.3.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.3.0.conv.bias", "neck.stack_bifpn_convs.4.bifpn_convs.4.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.4.0.conv.bias", "neck.stack_bifpn_convs.4.bifpn_convs.5.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.5.0.conv.bias", "neck.stack_bifpn_convs.4.bifpn_convs.6.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.6.0.conv.bias", "neck.stack_bifpn_convs.4.bifpn_convs.7.0.conv.weight", "neck.stack_bifpn_convs.4.bifpn_convs.7.0.conv.bias", "neck.stack_bifpn_convs.5.w1", "neck.stack_bifpn_convs.5.w2", "neck.stack_bifpn_convs.5.bifpn_convs.0.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.0.0.conv.bias", "neck.stack_bifpn_convs.5.bifpn_convs.1.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.1.0.conv.bias", "neck.stack_bifpn_convs.5.bifpn_convs.2.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.2.0.conv.bias", "neck.stack_bifpn_convs.5.bifpn_convs.3.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.3.0.conv.bias", "neck.stack_bifpn_convs.5.bifpn_convs.4.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.4.0.conv.bias", "neck.stack_bifpn_convs.5.bifpn_convs.5.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.5.0.conv.bias", "neck.stack_bifpn_convs.5.bifpn_convs.6.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.6.0.conv.bias", "neck.stack_bifpn_convs.5.bifpn_convs.7.0.conv.weight", "neck.stack_bifpn_convs.5.bifpn_convs.7.0.conv.bias". 
	size mismatch for neck.lateral_convs.0.conv.weight: copying a param with shape torch.Size([224, 56, 1, 1]) from checkpoint, the shape in current model is torch.Size([88, 56, 1, 1]).
	size mismatch for neck.lateral_convs.0.conv.bias: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([88]).
	size mismatch for neck.lateral_convs.1.conv.weight: copying a param with shape torch.Size([224, 112, 1, 1]) from checkpoint, the shape in current model is torch.Size([88, 112, 1, 1]).
	size mismatch for neck.lateral_convs.1.conv.bias: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([88]).
	size mismatch for neck.lateral_convs.2.conv.weight: copying a param with shape torch.Size([224, 160, 1, 1]) from checkpoint, the shape in current model is torch.Size([88, 160, 1, 1]).
	size mismatch for neck.lateral_convs.2.conv.bias: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([88]).
	size mismatch for neck.lateral_convs.3.conv.weight: copying a param with shape torch.Size([224, 272, 1, 1]) from checkpoint, the shape in current model is torch.Size([88, 272, 1, 1]).
	size mismatch for neck.lateral_convs.3.conv.bias: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([88]).
	size mismatch for neck.lateral_convs.4.conv.weight: copying a param with shape torch.Size([224, 448, 1, 1]) from checkpoint, the shape in current model is torch.Size([88, 448, 1, 1]).
	size mismatch for neck.lateral_convs.4.conv.bias: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([88]).
	size mismatch for neck.stack_bifpn_convs.0.bifpn_convs.0.0.conv.weight: copying a param with shape torch.Size([224, 224, 3, 3]) from checkpoint, the shape in current model is torch.Size([88, 88, 3, 3]).
》》》》》》》

**Comment by huangweiji2019** [comment]
and train.py line 184  
       " 'num_class': args.num_class"  is wrong,please check!!!

**Comment by inFreedom92** [comment]
> and train.py line 184
" 'num_class': args.num_class" is wrong,please check!!!

maybe changing it to 
`'num_class': args.num_classes`
would do.

**Comment by huangweiji2019** [comment]
There is something wrong with the code when training my dataset. It must be something wrong with the parameters of efficientdet.py file

**Comment by qtw1998** [comment]
> There is something wrong with the code when training my dataset. It must be something wrong with the parameters of efficientdet.py file

No, efficientdet.py is correct actually

**Comment by Borda** [comment]
@huangweiji2019 pls be nice...
